
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action Help;
	
	private global::Gtk.Action AboutAction;
	
	private global::Gtk.Action CloseAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.TextView _Result;
	
	private global::Gtk.HButtonBox hbuttonbox10;
	
	private global::Gtk.Button _buttonClear;
	
	private global::Gtk.HButtonBox hbuttonbox2;
	
	private global::Gtk.Button _buttonOne;
	
	private global::Gtk.Button _buttonTwo;
	
	private global::Gtk.Button _buttonThree;
	
	private global::Gtk.Button _buttonDivide;
	
	private global::Gtk.HButtonBox hbuttonbox4;
	
	private global::Gtk.Button _buttonFour;
	
	private global::Gtk.Button _buttonFive;
	
	private global::Gtk.Button _buttonSix;
	
	private global::Gtk.Button _buttonMultiply;
	
	private global::Gtk.HButtonBox hbuttonbox3;
	
	private global::Gtk.Button _buttonSeven;
	
	private global::Gtk.Button _buttonEight;
	
	private global::Gtk.Button _buttonNine;
	
	private global::Gtk.Button _buttonMinus;
	
	private global::Gtk.HButtonBox hbuttonbox5;
	
	private global::Gtk.Button _buttonZero;
	
	private global::Gtk.Button _buttonDecimal;
	
	private global::Gtk.Button _buttonAdd;
	
	private global::Gtk.Button _buttonCalculate;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, "<Alt><Mod2>f");
		this.Help = new global::Gtk.Action ("Help", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.Help.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.Help, "<Alt><Mod2>h");
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("Close"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Close");
		w1.Add (this.CloseAction, "<Primary><Mod2>x");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Nate's Calculator");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 50;
		this.DefaultHeight = 100;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='CloseAction' action='CloseAction'/></menu><menu name='Help' action='Help'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this._Result = new global::Gtk.TextView ();
		this._Result.WidthRequest = 100;
		this._Result.HeightRequest = 100;
		this._Result.CanFocus = true;
		this._Result.Name = "_Result";
		this._Result.AcceptsTab = false;
		this.vbox2.Add (this._Result);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this._Result]));
		w3.Position = 0;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox10 = new global::Gtk.HButtonBox ();
		this.hbuttonbox10.Name = "hbuttonbox10";
		this.hbuttonbox10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox10.Gtk.ButtonBox+ButtonBoxChild
		this._buttonClear = new global::Gtk.Button ();
		this._buttonClear.WidthRequest = 50;
		this._buttonClear.HeightRequest = 0;
		this._buttonClear.CanFocus = true;
		this._buttonClear.Name = "_buttonClear";
		this._buttonClear.UseUnderline = true;
		this._buttonClear.Label = global::Mono.Unix.Catalog.GetString ("AC");
		this.hbuttonbox10.Add (this._buttonClear);
		global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox10 [this._buttonClear]));
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add (this.hbuttonbox10);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox10]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this._buttonOne = new global::Gtk.Button ();
		this._buttonOne.CanFocus = true;
		this._buttonOne.Name = "_buttonOne";
		this._buttonOne.UseUnderline = true;
		this._buttonOne.Label = global::Mono.Unix.Catalog.GetString ("1");
		this.hbuttonbox2.Add (this._buttonOne);
		global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this._buttonOne]));
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this._buttonTwo = new global::Gtk.Button ();
		this._buttonTwo.CanFocus = true;
		this._buttonTwo.Name = "_buttonTwo";
		this._buttonTwo.UseUnderline = true;
		this._buttonTwo.Label = global::Mono.Unix.Catalog.GetString ("2");
		this.hbuttonbox2.Add (this._buttonTwo);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this._buttonTwo]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this._buttonThree = new global::Gtk.Button ();
		this._buttonThree.CanFocus = true;
		this._buttonThree.Name = "_buttonThree";
		this._buttonThree.UseUnderline = true;
		this._buttonThree.Label = global::Mono.Unix.Catalog.GetString ("3");
		this.hbuttonbox2.Add (this._buttonThree);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this._buttonThree]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this._buttonDivide = new global::Gtk.Button ();
		this._buttonDivide.CanFocus = true;
		this._buttonDivide.Name = "_buttonDivide";
		this._buttonDivide.UseUnderline = true;
		this._buttonDivide.Label = global::Mono.Unix.Catalog.GetString ("/");
		this.hbuttonbox2.Add (this._buttonDivide);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this._buttonDivide]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		w9.Padding = ((uint)(2));
		this.vbox2.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		w10.Padding = ((uint)(2));
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox4 = new global::Gtk.HButtonBox ();
		this.hbuttonbox4.Name = "hbuttonbox4";
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this._buttonFour = new global::Gtk.Button ();
		this._buttonFour.CanFocus = true;
		this._buttonFour.Name = "_buttonFour";
		this._buttonFour.UseUnderline = true;
		this._buttonFour.Label = global::Mono.Unix.Catalog.GetString ("4");
		this.hbuttonbox4.Add (this._buttonFour);
		global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this._buttonFour]));
		w11.Expand = false;
		w11.Fill = false;
		w11.Padding = ((uint)(2));
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this._buttonFive = new global::Gtk.Button ();
		this._buttonFive.CanFocus = true;
		this._buttonFive.Name = "_buttonFive";
		this._buttonFive.UseUnderline = true;
		this._buttonFive.Label = global::Mono.Unix.Catalog.GetString ("5");
		this.hbuttonbox4.Add (this._buttonFive);
		global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this._buttonFive]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(2));
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this._buttonSix = new global::Gtk.Button ();
		this._buttonSix.CanFocus = true;
		this._buttonSix.Name = "_buttonSix";
		this._buttonSix.UseUnderline = true;
		this._buttonSix.Label = global::Mono.Unix.Catalog.GetString ("6");
		this.hbuttonbox4.Add (this._buttonSix);
		global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this._buttonSix]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		w13.Padding = ((uint)(2));
		// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
		this._buttonMultiply = new global::Gtk.Button ();
		this._buttonMultiply.CanFocus = true;
		this._buttonMultiply.Name = "_buttonMultiply";
		this._buttonMultiply.UseUnderline = true;
		this._buttonMultiply.Label = global::Mono.Unix.Catalog.GetString ("*");
		this.hbuttonbox4.Add (this._buttonMultiply);
		global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this._buttonMultiply]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		w14.Padding = ((uint)(2));
		this.vbox2.Add (this.hbuttonbox4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox4]));
		w15.Position = 3;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox3 = new global::Gtk.HButtonBox ();
		this.hbuttonbox3.Name = "hbuttonbox3";
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this._buttonSeven = new global::Gtk.Button ();
		this._buttonSeven.CanFocus = true;
		this._buttonSeven.Name = "_buttonSeven";
		this._buttonSeven.UseUnderline = true;
		this._buttonSeven.Label = global::Mono.Unix.Catalog.GetString ("7");
		this.hbuttonbox3.Add (this._buttonSeven);
		global::Gtk.ButtonBox.ButtonBoxChild w16 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this._buttonSeven]));
		w16.Expand = false;
		w16.Fill = false;
		w16.Padding = ((uint)(2));
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this._buttonEight = new global::Gtk.Button ();
		this._buttonEight.CanFocus = true;
		this._buttonEight.Name = "_buttonEight";
		this._buttonEight.UseUnderline = true;
		this._buttonEight.Label = global::Mono.Unix.Catalog.GetString ("8");
		this.hbuttonbox3.Add (this._buttonEight);
		global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this._buttonEight]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		w17.Padding = ((uint)(2));
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this._buttonNine = new global::Gtk.Button ();
		this._buttonNine.CanFocus = true;
		this._buttonNine.Name = "_buttonNine";
		this._buttonNine.UseUnderline = true;
		this._buttonNine.Label = global::Mono.Unix.Catalog.GetString ("9");
		this.hbuttonbox3.Add (this._buttonNine);
		global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this._buttonNine]));
		w18.Position = 2;
		w18.Expand = false;
		w18.Fill = false;
		w18.Padding = ((uint)(2));
		// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
		this._buttonMinus = new global::Gtk.Button ();
		this._buttonMinus.CanFocus = true;
		this._buttonMinus.Name = "_buttonMinus";
		this._buttonMinus.UseUnderline = true;
		this._buttonMinus.Label = global::Mono.Unix.Catalog.GetString ("-");
		this.hbuttonbox3.Add (this._buttonMinus);
		global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this._buttonMinus]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		w19.Padding = ((uint)(2));
		this.vbox2.Add (this.hbuttonbox3);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox3]));
		w20.Position = 4;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbuttonbox5 = new global::Gtk.HButtonBox ();
		this.hbuttonbox5.Name = "hbuttonbox5";
		this.hbuttonbox5.Homogeneous = true;
		this.hbuttonbox5.Spacing = 10;
		this.hbuttonbox5.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this._buttonZero = new global::Gtk.Button ();
		this._buttonZero.CanFocus = true;
		this._buttonZero.Name = "_buttonZero";
		this._buttonZero.UseUnderline = true;
		this._buttonZero.Label = global::Mono.Unix.Catalog.GetString ("0");
		this.hbuttonbox5.Add (this._buttonZero);
		global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this._buttonZero]));
		w21.Expand = false;
		w21.Fill = false;
		w21.Padding = ((uint)(2));
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this._buttonDecimal = new global::Gtk.Button ();
		this._buttonDecimal.CanFocus = true;
		this._buttonDecimal.Name = "_buttonDecimal";
		this._buttonDecimal.UseUnderline = true;
		this._buttonDecimal.Label = global::Mono.Unix.Catalog.GetString (".");
		this.hbuttonbox5.Add (this._buttonDecimal);
		global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this._buttonDecimal]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		w22.Padding = ((uint)(2));
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this._buttonAdd = new global::Gtk.Button ();
		this._buttonAdd.CanFocus = true;
		this._buttonAdd.Name = "_buttonAdd";
		this._buttonAdd.UseUnderline = true;
		this._buttonAdd.Label = global::Mono.Unix.Catalog.GetString ("+");
		this.hbuttonbox5.Add (this._buttonAdd);
		global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this._buttonAdd]));
		w23.Position = 2;
		w23.Expand = false;
		w23.Fill = false;
		w23.Padding = ((uint)(2));
		// Container child hbuttonbox5.Gtk.ButtonBox+ButtonBoxChild
		this._buttonCalculate = new global::Gtk.Button ();
		this._buttonCalculate.CanFocus = true;
		this._buttonCalculate.Name = "_buttonCalculate";
		this._buttonCalculate.UseUnderline = true;
		this._buttonCalculate.Label = global::Mono.Unix.Catalog.GetString ("=");
		this.hbuttonbox5.Add (this._buttonCalculate);
		global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox5 [this._buttonCalculate]));
		w24.Position = 3;
		w24.Expand = false;
		w24.Fill = false;
		w24.Padding = ((uint)(2));
		this.vbox2.Add (this.hbuttonbox5);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox5]));
		w25.Position = 5;
		w25.Expand = false;
		w25.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w26.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this._buttonClear.Clicked += new global::System.EventHandler (this.OnButtonClearClicked);
		this._buttonOne.Clicked += new global::System.EventHandler (this.OnButtonOneClicked);
		this._buttonTwo.Clicked += new global::System.EventHandler (this.OnButtonTwoClicked);
		this._buttonThree.Clicked += new global::System.EventHandler (this.OnButtonThreeClicked);
		this._buttonDivide.Clicked += new global::System.EventHandler (this.OnButtonDivideClicked);
		this._buttonFour.Clicked += new global::System.EventHandler (this.OnButtonFourClicked);
		this._buttonFive.Clicked += new global::System.EventHandler (this.OnButtonFiveClicked);
		this._buttonSix.Clicked += new global::System.EventHandler (this.OnButtonSixClicked);
		this._buttonMultiply.Clicked += new global::System.EventHandler (this.OnButtonMultiplyClicked);
		this._buttonSeven.Clicked += new global::System.EventHandler (this.OnButtonSevenClicked);
		this._buttonEight.Clicked += new global::System.EventHandler (this.OnButtonEightClicked);
		this._buttonNine.Clicked += new global::System.EventHandler (this.OnButtonNineClicked);
		this._buttonMinus.Clicked += new global::System.EventHandler (this.OnButtonMinusClicked);
		this._buttonZero.Clicked += new global::System.EventHandler (this.OnButtonZeroClicked);
		this._buttonDecimal.Clicked += new global::System.EventHandler (this.OnButtonDecimalClicked);
		this._buttonAdd.Clicked += new global::System.EventHandler (this.OnButtonAddClicked);
		this._buttonCalculate.Clicked += new global::System.EventHandler (this.OnButtonCalculateClicked);
	}
}
